name: CIWindows
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build_windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@main
      with:
        submodules: 'true'
    - uses: ilammy/msvc-dev-cmd@v1
    - name: build
      run: .\proc\win\cl.bat