name: CILinux
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@main
    - name: build
      run: bash ./proc/linux/gcc.sh
