name: CILinux
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@main
        with:
          submodules: 'true'
    - name: build
      run: bash ./proc/linux/gcc.sh
