name: CILinux
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    
    steps:

    - name: deps
      run: git clone https://github.com/MrFrenik/gunslinger.git third_party/include/gs
    - name: Checkout repository
      uses: actions/checkout@main
    - name: ls
      run: ls source/
    - name: build
      run: bash ./gcc.sh
